import { expect, it } from "vitest";
import { app, completeSetup } from "./lib/harness";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { REPO_ROOT } from "./lib/devApp";

it("follows a native Codex name arriving while idle and preserves a manual rename", async () => {
  const dev = await app();
  await completeSetup(dev);
  const id = "e2e-native-codex-name";
  const cwd = mkdtempSync(path.join(tmpdir(), "boite-native-name-"));
  await dev.js(`
    const invoke = window.__TAURI__.core.invoke;
    await invoke('records_project_create', {params:{project:{id:'native-name-project',name:'Codex names',cwd:${JSON.stringify(cwd)},icon:null,archived:false,worktrees:false}}});
    await invoke('records_thread_create', {params:{thread:{id:'${id}',projectId:'native-name-project',label:'Codex #1',title:'please fix the thread names',cmd:'node',args:['-e','setInterval(()=>{},1000)'],iconKey:'terminal',sessionId:'native-session',status:'idle',exitCode:null,ptyId:null,createdAt:Date.now(),keepAwake:true}}});
    location.reload(); return true;
  `);
  await dev.waitFor("return !!window.__boite");
  await completeSetup(dev);
  await dev.waitFor(`return !!document.querySelector('li[data-thread-id="${id}"] button[data-nav-row]')`);
  await dev.click(`li[data-thread-id="${id}"] button[data-nav-row]`);
  await dev.waitFor(`return window.__boite.thread('${id}').running`);
  await dev.js(`
    const {app} = await import('/src/lib/app/store.svelte.ts');
    const {startSessionMonitor} = await import('/src/lib/features/thread/session-monitor.svelte.ts');
    const row = app.threadById('${id}');
    window.__nativeName = null;
    window.__nativePolls = 0;
    window.__nativeMonitor = startSessionMonitor({
      threadId:row.id,cwd:${JSON.stringify(cwd)},kind:'codex',since:Date.now(),targetPtyId:row.ptyId,
      isPtyCurrent:(id)=>row.ptyId===id,lastActivityAt:()=>0,
      detector:async(cwd,after,exclude,pty,sessionId)=>{
        if(sessionId !== 'native-session') throw new Error('native name poll must address the bound session');
        window.__nativePolls++;
        return {id:sessionId,mtimeMs:0,title:null,name:window.__nativeName};
      }
    });
    return true;
  `);
  const label = () => dev.js<string>(`return document.querySelector('li[data-thread-id="${id}"]').innerText`);
  await dev.waitFor("return window.__nativePolls > 0");
  expect(await label()).toContain("please fix the thread names");
  await dev.js("window.__nativeName='Fix Codex thread names'; return true;");
  await dev.waitForText(label, text => text.includes("Fix Codex thread names"));
  await dev.waitForText(() => dev.db(`SELECT title FROM threads WHERE id='${id}'`), text => text.includes("Fix Codex thread names"));
  if (process.env.BOITE_E2E_SHOT) await dev.screenshot(process.env.BOITE_E2E_SHOT);
  await dev.js("window.__nativeName='Refine Codex titles'; return true;");
  await dev.waitForText(label, text => text.includes("Refine Codex titles"));
  await dev.js(`
    const {app}=await import('/src/lib/app/store.svelte.ts');
    await app.renameThread('${id}','My chosen name');
    window.__nativeName='Must not overwrite';
    window.__pollBeforeRename=window.__nativePolls;
    return true;
  `);
  await dev.waitFor("return window.__nativePolls > window.__pollBeforeRename");
  expect(await label()).toContain("My chosen name");
  await dev.js("window.__nativeMonitor.stop(); location.reload(); return true;");
  await dev.waitFor(`return !!document.querySelector('li[data-thread-id="${id}"]')`);
  expect(await label()).toContain("My chosen name");
});

it.skipIf(process.env.BOITE_E2E_CODEX !== "1")("displays a title generated by the installed Codex CLI", async () => {
  const dev = await app();
  await completeSetup(dev);
  const id = "e2e-generated-codex-name";
  await dev.js(`
    const invoke=window.__TAURI__.core.invoke;
    await invoke('records_project_create',{params:{project:{id:'generated-name-project',name:'Native Codex generation',cwd:${JSON.stringify(REPO_ROOT)},icon:null,archived:false,worktrees:false}}});
    await invoke('records_thread_create',{params:{thread:{id:'${id}',projectId:'generated-name-project',label:'Codex title generation',title:null,cmd:'codex',args:[],iconKey:'codex',sessionId:null,status:'idle',exitCode:null,ptyId:null,createdAt:Date.now(),keepAwake:true}}});
    location.reload(); return true;
  `);
  await dev.waitFor("return !!window.__boite");
  await completeSetup(dev);
  await dev.waitFor(`return !!document.querySelector('li[data-thread-id="${id}"] button[data-nav-row]')`);
  await dev.click(`li[data-thread-id="${id}"] button[data-nav-row]`);
  const screen = () => dev.js<string>(`
    const {liveTerminal,terminalText}=await import('/src/lib/shared/terminals.ts');
    const term=liveTerminal('${id}'); return term ? terminalText(term) : '';
  `);
  await dev.waitForText(screen, text => text.includes("context") || text.includes("Context"));
  await dev.js(`
    const {liveTerminal}=await import('/src/lib/shared/terminals.ts');
    liveTerminal('${id}').input('Réponds uniquement OK, sans outil et sans modifier de fichier.',true);
    return true;
  `);
  await dev.waitForText(screen, text => text.includes("sans modifier"));
  await dev.js(`
    const {liveTerminal}=await import('/src/lib/shared/terminals.ts');
    liveTerminal('${id}').textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}));
    return true;
  `);
  await dev.waitFor(`
    const row=window.__boite.thread('${id}');
    if(!row?.sessionId) return false;
    const hit=await window.__TAURI__.core.invoke('find_codex_session',{cwd:${JSON.stringify(REPO_ROOT)},afterUnixMs:0,excludeIds:[],sessionId:row.sessionId});
    return !!hit?.name && row.title === hit.name && !hit.name.startsWith('Réponds uniquement OK,');
  `, 120_000);
  if (process.env.BOITE_E2E_SHOT) await dev.screenshot(process.env.BOITE_E2E_SHOT);
});
